language: python
sudo: required
dist: trusty
services:
  - docker
python:
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
  - sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make-builddeps
  - sudo apt-get update
# install binary deps
  - sudo apt-get install -y $(tests/daily_runs/get_binary_depends ubuntu-make)
# install tests requirements
  - sudo tests/daily_runs/install_build_tests_depends
install: "" # we don't want to use virtualenv (see below)
# as we can't use a system virtualenv anymore in travis CI and that
# python-gobject isn't installable in pypy, we have to use system libraries
# instead for both uncompiled and compiled modules.
# The easiest way without hacking PYTHONPATH, PYTHONHOME is to use the system
# python version by prepending it in the PATH.
env:
  - TESTFOLDER="pep8 small"
  - TESTFOLDER="medium"
script: PATH="/usr/bin:$PATH" ./runtests $TESTFOLDER
