language: python
python:
  - "3.4"
virtualenv:
  system_site_packages: true

dist: trusty
sudo: required

services:
  - docker

install:
  - sudo apt-get update -q
  - sudo apt install -y gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-apt
  - pip install -r requirements.txt
env:
  - TESTFOLDER="pep8 small"
  - TESTFOLDER="medium"
script: PATH="/usr/bin:$PATH" ./runtests $TESTFOLDER
