#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (C) 2014 Canonical
#
# Authors:
#  Didier Roche
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import argparse
import logging
from textwrap import dedent
import udtc
from udtc.network.download_center import DownloadCenter

logger = logging.getLogger("ubuntu developer tools center")

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Deploy and setup developers environment easily on ubuntu",
                                     epilog=dedent("""\
                                         Note that you can also configure different debug logs behaviors using LOG_CFG
                                         pointing to a log yaml profile.
                                         """))
    parser.add_argument("-v", "--verbose", action="count", default=0, help="increase output verbosity (2 levels)")
    args = parser.parse_args()

    # setup logging level if set by the command line
    if args.verbose == 1:
        udtc.setup_logging(level=logging.INFO)
    elif args.verbose > 1:
        udtc.setup_logging(level=logging.DEBUG)
    else:
        udtc.setup_logging()


    DownloadCenter(["http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python"], lambda x: print(x))