#!/bin/sh
# Copyright (C) 2014 Canonical
#
# Authors:
#  Didier Roche
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# setup dbus environment and launch a command, pwd being the udtc dir.
# Start command in async mode
[ ! -f /tmp/dbus-file ] && dbus-launch > /tmp/dbus-file
export $(cat /tmp/dbus-file)
cd $1
shift
. env/bin/activate
$@ &
