#!/bin/sh

# setup dbus environment and launch a command, pwd being the udtc dir
[ ! -f /tmp/dbus-file ] && dbus-launch > /tmp/dbus-file
export $(cat /tmp/dbus-file)
cd $1
shift
. env/bin/activate
$@
