#!/bin/sh
# autopkgtest check: Run all umake tests, including coverage
# (C) 2014 Canonical Ltd.
# Author: Didier Roche <didrocks@ubuntu.com>

set -e

# add to docker groups and log in as such
sudo addgroup ubuntu docker

# Run all tests, including docker, integration and unit ones, with coverage
sudo su ubuntu -c "./runtests --coverage small"
