#!/bin/bash
# Author: Didier Roche <didrocks@ubuntu.com>
set -e
. `dirname $0`/utils

# skip tests if not requested
skip_if_no_in_list

# require compiz to run as we might right large tests
wait_for_compiz

run_tests $TESTS

publish_results
