#!/bin/bash
# Author: Didier Roche <didrocks@ubuntu.com>
set -e
. `dirname $0`/utils

# skip tests if not requested
skip_if_no_in_list

# require user session to run as we might have large tests
wait_for_user_session

run_tests $TESTS

publish_results
