#!/bin/bash
# setup an ubuntu-desktop machine with autologin and dependencies
# Author: Didier Roche <didrocks@ubuntu.com>
set -e
. `dirname $0`/utils

if [ -n "$ADT_REBOOT_MARK" ]; then
    exit 0
fi

# configure docker
sudo -n addgroup $(whoami) docker
# TODO: get it from /etc/environment
echo export http_proxy="http://squid.internal:3128" | sudo -n tee /etc/default/docker.io

# workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808203
sudo -n rm -f /etc/dpkg/dpkg.cfg.d/pkg-config-hook-config

# enable autologin to get unity started
if [ ! -r /etc/lightdm/lightdm.conf.d/umaketests.conf ]; then
    sudo -n mkdir -p /etc/lightdm/lightdm.conf.d
    cat << EOF | sudo -n tee /etc/lightdm/lightdm.conf.d/umaketests.conf
[SeatDefaults]
autologin-user=ubuntu
EOF
fi

# enable localhost ssh connection without pass
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

# ubuntu-make was installed for its dependencies
# remove it if we are not running system tests (we only needed its dep)
if [ "$(is_package_test)" = "false" ]; then
    sudo -n apt remove -y ubuntu-make
fi

# store ubuntu make version and packages
config_dir="$ADT_ARTIFACTS/config"
mkdir -p $config_dir

# discover target: package/branch, origin
if [ "$(is_package_test)" = "true" ]; then
    # clean the source package to ensure we don't have duplicated files after
    # build for sloccount
    debian/rules clean
    type="system"
    origin="$(apt-cache policy ubuntu-make | sed -n '/\*\*\*/ {n;p}' | cut -d' ' -f 10)"
    [ -z "$origin" ] && origin="Local package"
    version="$(umake --version)'"
else
    type="branch"
    upstream_short="$(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD))"
    IFS=/ read repo branch <<< $upstream_short
    repo_url=$(git config --get remote.${repo}.url)
    origin="${repo_url} $branch"
    version="$(bin/umake --version)'"
fi

cat << EOF | tee "$config_dir/version"
{
    'target': {
       'type': '$type',
       'origin': '$origin',
       'version': '$version',
    },
    'date': {
        'timestamp': '$(date +%s)',
        'utc': '$(date -u)'
    },
    'arch': '$(arch)'
}
EOF
dpkg -l > "$config_dir/packages_list"

echo -e "\nStats:"
sloccount * | head -n -17 | tail -17 | tee "$config_dir/stats"

# remove umake directory for coverage reporting on real used files
if [ "$type" = "system" ]; then
    rm -r umake/
fi

sudo -n /tmp/autopkgtest-reboot ready
