#!/bin/bash
# Author: Didier Roche <didrocks@ubuntu.com>
set -e
. `dirname $0`/utils

# skip tests if not requested.
skip_if_no_in_list

./runtests --publish --coverage $(add_runtests_opts) small

publish_results
