#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -f "$(which register-python-argcomplete3)" ]; then
            register-python-argcomplete3 umake > /etc/bash_completion.d/umake
        else
            register-python-argcomplete umake > /etc/bash_completion.d/umake
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

