name: ubuntu-make
version: 'master'
summary: Setup your development environment on ubuntu easily
description: |
  Ubuntu Make provides a set of functionality to setup,
  maintain and personalize your developer environment easily. It will handle
  all dependencies, even those which aren't in Ubuntu itself, and install
  latest versions of the desired and recommended tools.
  .
  This is the latest master from ubuntu make, freshly built from
  https://github.com/ubuntu/ubuntu-make. It may contain even unreleased
  features!
grade: stable
confinement: classic
base: core20
compression: lzo

apps:
  umake:
    command: bin/umake-wrapper
    completer: umake-completion
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$PYTHONPATH

parts:
  umake:
    source: .
    plugin: python
    build-packages:
      - libapt-pkg-dev
      - gettext
      - python3-apt
      - python3-argcomplete
      - python3-gi
      - python3-gnupg
      - python3-setuptools
      - python3-pytest
      - python3-pycodestyle
      - python3-pexpect
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - dbus-x11
      - fakeroot
      - help2man
    stage-packages:
      - python3-apt
      - python3-argcomplete
      - python3-gi
      - python3-gnupg
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - libstdc++6
      - libc6
      - libuuid1
      - libreadline8
      - libtinfo5
      - libselinux1
      - libpcre3
      - libudev1
      - zlib1g
      - libbz2-1.0
      - libgcc1
      - liblzma5
      - libblkid1
      - libmount1
      - libncursesw5
      - libdb5.3
    build-environment:
      - SNAPCRAFT_PYTHON_VENV_ARGS: "--system-site-packages"
  python3:
    plugin: nil
    source: .
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
  umake-completion:
    plugin: dump
    source: snap/local
    stage:
      - umake-completion
  umake-wrapper:
    source: snap/local
    plugin: dump
    organize:
      umake-wrapper: bin/umake-wrapper
