name: ubuntu-make
version: 'master'
summary: Setup your development environment on ubuntu easily
description: |
  Ubuntu Make provides a set of functionality to setup,
  maintain and personalize your developer environment easily. It will handle
  all dependencies, even those which aren't in Ubuntu itself, and install
  latest versions of the desired and recommended tools.
  .
  This is the latest master from ubuntu make, freshly built from
  https://github.com/ubuntu/ubuntu-make. It may contain even unreleased
  features!
grade: stable
confinement: classic
base: core18

apps:
  umake:
    command: bin/umake-wrapper
    completer: umake-completion

parts:
  umake-completion:
    plugin: dump
    source: snap
    stage:
      - umake-completion
  umake-wrapper:
    plugin: dump
    source: snap/
    organize:
      umake-wrapper: bin/umake-wrapper
  umake:
    source: .
    plugin: python
    organize:
      lib/python3/dist-packages/umake: lib/python3.6/site-packages/umake
    after:
      - umake-wrapper
    build-packages:
      - gettext
      - python3-apt
      - python3-argcomplete
      - python3-gi
      - python3-gnupg
      - python3-setuptools
      - python3-nose
      - python3-nose-cov
      - python3-nose-json
      - python3-pep8
      - python3-pexpect
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - dbus-x11
      - fakeroot
      - help2man
    stage-packages:
      - python3-apt
      - python3-argcomplete
      - python3-gi
      - python3-gnupg
      - python3-progressbar
      - python3-yaml
      - python3-requests
      - python3-xdg
      - libstdc++6
      - libc6
      - libuuid1
      - libreadline7
      - libtinfo5
      - libselinux1
      - libpcre3
      - libudev1
      - zlib1g
      - libbz2-1.0
      - libgcc1
      - liblzma5
      - libblkid1
      - libmount1
      - libncursesw5
      - libdb5.3