
<!DOCTYPE html>
<!--
 | Generated by Apache Maven Doxia Site Renderer 1.7.4 at 2017-08-09
 | Rendered using Apache Maven Fluido Skin 1.6
-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Brett Porter" />
    <meta name="author" content="Jason van Zyl" />
    <meta name="author" content="John Casey" />
    <meta name="author" content="Manfred Moser" />
    <meta name="Date-Revision-yyyymmdd" content="20170809" />
    <meta http-equiv="Content-Language" content="en" />
    <title>Maven &#x2013; Download Apache Maven</title>
    <link rel="stylesheet" href="./css/apache-maven-fluido-1.6.min.css" />
    <link rel="stylesheet" href="./css/site.css" />
    <link rel="stylesheet" href="./css/print.css" media="print" />
      <script type="text/javascript" src="./js/apache-maven-fluido-1.6.min.js"></script>
      <!-- Google Analytics -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-140879-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
      </head>
    <body class="topBarDisabled">
      <div class="container-fluid">
      <div id="banner">
        <div class="pull-left"><a href="https://www.apache.org/" id="bannerLeft"><img src="images/apache-maven-project.png"  alt="Apache Maven Site"/></a></div>
        <div class="pull-right"><a href="./" id="bannerRight"><img src="images/maven-logo-black-on-white.png" /></a></div>
        <div class="clear"><hr/></div>
      </div>

      <div id="breadcrumbs">
        <ul class="breadcrumb">
        <li class=""><a href="https://www.apache.org/" class="externalLink" title="Apache">Apache</a><span class="divider">/</span></li>
      <li class=""><a href="index.html" title="Maven">Maven</a><span class="divider">/</span></li>
    <li class="active ">Download Apache Maven</li>
        <li id="publishDate" class="pull-right">Last Published: 2017-08-09</li>
        </ul>
      </div>
      <div class="row-fluid">
        <div id="leftColumn" class="span2">
          <div class="well sidebar-nav">
<ul class="nav nav-list">
          <li class="nav-header">Main</li>
    <li><a href="index.html" title="Welcome"><span class="none"></span>Welcome</a>  </li>
    <li><a href="https://www.apache.org/licenses/" class="externalLink" title="License"><span class="none"></span>License</a>  </li>
    <li class="active"><a href="#"><span class="none"></span>Download</a>
  </li>
    <li><a href="install.html" title="Install"><span class="none"></span>Install</a>  </li>
    <li><a href="configure.html" title="Configure"><span class="none"></span>Configure</a>  </li>
    <li><a href="run.html" title="Run"><span class="none"></span>Run</a>  </li>
    <li><a href="ide.html" title="IDE Integration"><span class="none"></span>IDE Integration</a>  </li>
          <li class="nav-header">About Maven</li>
    <li><a href="what-is-maven.html" title="What is Maven?"><span class="none"></span>What is Maven?</a>  </li>
    <li><a href="maven-features.html" title="Features"><span class="none"></span>Features</a>  </li>
    <li><a href="general.html" title="FAQ"><span class="none"></span>FAQ</a>  </li>
    <li><a href="support-and-training.html" title="Support and Training"><span class="none"></span>Support and Training</a>  </li>
          <li class="nav-header">Documentation</li>
    <li><a href="plugins/index.html" title="Maven Plugins"><span class="none"></span>Maven Plugins</a>  </li>
    <li><a href="guides/index.html" title="Index (category)"><span class="none"></span>Index (category)</a>  </li>
    <li><a href="run-maven/index.html" title="Running Maven"><span class="none"></span>Running Maven</a>  </li>
    <li><a href="users/index.html" title="User Centre"><span class="icon-chevron-right"></span>User Centre</a>  </li>
    <li><a href="plugin-developers/index.html" title="Plugin Developer Centre"><span class="icon-chevron-right"></span>Plugin Developer Centre</a>  </li>
    <li><a href="repository/index.html" title="Maven Central Repository"><span class="none"></span>Maven Central Repository</a>  </li>
    <li><a href="developers/index.html" title="Maven Developer Centre"><span class="none"></span>Maven Developer Centre</a>  </li>
    <li><a href="articles.html" title="Books and Resources"><span class="none"></span>Books and Resources</a>  </li>
    <li><a href="security.html" title="Security"><span class="none"></span>Security</a>  </li>
          <li class="nav-header">Community</li>
    <li><a href="community.html" title="Community Overview"><span class="none"></span>Community Overview</a>  </li>
    <li><a href="guides/development/guide-helping.html" title="How to Contribute"><span class="none"></span>How to Contribute</a>  </li>
    <li><a href="guides/mini/guide-maven-evangelism.html" title="Maven Repository"><span class="none"></span>Maven Repository</a>  </li>
    <li><a href="users/getting-help.html" title="Getting Help"><span class="none"></span>Getting Help</a>  </li>
    <li><a href="issue-tracking.html" title="Issue Tracking"><span class="none"></span>Issue Tracking</a>  </li>
    <li><a href="source-repository.html" title="Source Repository"><span class="none"></span>Source Repository</a>  </li>
    <li><a href="team-list.html" title="The Maven Team"><span class="none"></span>The Maven Team</a>  </li>
          <li class="nav-header">Project Documentation</li>
    <li><a href="project-info.html" title="Project Information"><span class="icon-chevron-right"></span>Project Information</a>  </li>
          <li class="nav-header">Maven Projects</li>
    <li><a href="archetype/index.html" title="Archetype"><span class="none"></span>Archetype</a>  </li>
    <li><a href="resolver/index.html" title="Artifact Resolver"><span class="none"></span>Artifact Resolver</a>  </li>
    <li><a href="doxia/index.html" title="Doxia"><span class="none"></span>Doxia</a>  </li>
    <li><a href="jxr/index.html" title="JXR"><span class="none"></span>JXR</a>  </li>
    <li><a href="ref/current" title="Maven"><span class="none"></span>Maven</a>  </li>
    <li><a href="pom/index.html" title="Parent POMs"><span class="none"></span>Parent POMs</a>  </li>
    <li><a href="plugins/index.html" title="Plugins"><span class="none"></span>Plugins</a>  </li>
    <li><a href="plugin-testing/index.html" title="Plugin Testing"><span class="none"></span>Plugin Testing</a>  </li>
    <li><a href="plugin-tools/index.html" title="Plugin Tools"><span class="none"></span>Plugin Tools</a>  </li>
    <li><a href="apache-resource-bundles/index.html" title="Resource Bundles"><span class="none"></span>Resource Bundles</a>  </li>
    <li><a href="scm/index.html" title="SCM"><span class="none"></span>SCM</a>  </li>
    <li><a href="shared/index.html" title="Shared Components"><span class="none"></span>Shared Components</a>  </li>
    <li><a href="skins/index.html" title="Skins"><span class="none"></span>Skins</a>  </li>
    <li><a href="surefire/index.html" title="Surefire"><span class="none"></span>Surefire</a>  </li>
    <li><a href="wagon/index.html" title="Wagon"><span class="none"></span>Wagon</a>  </li>
          <li class="nav-header">ASF</li>
    <li><a href="https://www.apache.org/foundation/how-it-works.html" class="externalLink" title="How Apache Works"><span class="none"></span>How Apache Works</a>  </li>
    <li><a href="https://www.apache.org/foundation/" class="externalLink" title="Foundation"><span class="none"></span>Foundation</a>  </li>
    <li><a href="https://www.apache.org/foundation/sponsorship.html" class="externalLink" title="Sponsoring Apache"><span class="none"></span>Sponsoring Apache</a>  </li>
    <li><a href="https://www.apache.org/foundation/thanks.html" class="externalLink" title="Thanks"><span class="none"></span>Thanks</a>  </li>
  </ul>
<form id="search-form" action="https://www.google.com/search" method="get" >
      <input value="https://maven.apache.org" name="sitesearch" type="hidden"/>
  <input class="search-query" name="q" id="query" type="text" />
</form>
<script type="text/javascript">asyncJs( 'https://cse.google.com/brand?form=search-form' )</script>
          <hr />
          <div id="poweredBy">
          <script type="text/javascript">asyncJs( 'https://apis.google.com/js/plusone.js' )</script>
        <div class="g-plusone" data-href="https://maven.apache.org/" data-size="tall" ></div>
                  <div class="clear"></div>
              <div class="clear"></div>
              <div class="clear"></div>
              <div class="clear"></div>
  <a href="http://maven.apache.org/" title="Built by Maven" class="poweredBy"><img class="builtBy" alt="Built by Maven" src="./images/logos/maven-feather.png" /></a>
              </div>
          </div>
        </div>
        <div id="bodyColumn"  class="span10" >


    <div class="section">
<h2><a name="Downloading_Apache_Maven_3.5.0"></a>Downloading Apache Maven 3.5.0</h2>


<p>Apache Maven 3.5.0 is the latest release and recommended version for all users.</p>

<p>

          The currently selected download mirror is
          <b>http://it.apache.contactlab.it/</b>.
          If you encounter a problem with this mirror,
          please select another mirror.
          If all mirrors are failing, there are
          <i>backup</i>
          mirrors
          (at the end of the mirrors list) that should be available.
            You may also consult the
          <a class="externalLink" href="https://www.apache.org/mirrors/">complete list of
            mirrors.</a>

        </p>

        <form action="" method="get" id="SelectMirror">
          Other mirrors:
          <select name="Preferred">

            <option value="http://apache.panu.it/">http://apache.panu.it/</option>

            <option value="http://it.apache.contactlab.it/">http://it.apache.contactlab.it/</option>

            <option value="http://mirror.nohup.it/apache/">http://mirror.nohup.it/apache/</option>

            <option value="ftp://ftp.panu.it/pub/mirrors/apache/">ftp://ftp.panu.it/pub/mirrors/apache/</option>

            <option value="ftp://mirror.nohup.it/apache/">ftp://mirror.nohup.it/apache/</option>

            <option value="http://www-eu.apache.org/dist/">http://www-eu.apache.org/dist/ (backup)</option>

            <option value="http://www-us.apache.org/dist/">http://www-us.apache.org/dist/ (backup)</option>

          </select>
          <input type="submit" value="Change" />
        </form>

      <a name="Requirements"></a>
      <a name="Requirements"></a>
<div class="section" id="Requirements">
<h3><a name="System_Requirements"></a>System Requirements</h3>

<p>
          </p>
<table border="0" class="table table-striped">

<tr class="a">

<td><b>Java Development Kit (JDK)</b></td>

<td>Maven 3.3+ require JDK 1.7 or above to execute - they still allows you to build against 1.3 and other JDK versions
              <a href="/guides/mini/guide-using-toolchains.html">by Using Toolchains</a></td>
            </tr>

<tr class="b">

<td><b>Memory</b></td>

<td>No minimum requirement</td>
            </tr>

<tr class="a">

<td><b>Disk</b></td>

<td>Approximately 10MB is required for the Maven installation itself. In addition to that, additional disk space will
              be used for your local Maven repository. The size of your local repository will vary depending on usage but expect at
              least 500MB.</td>
            </tr>

<tr class="b">

<td><b>Operating System</b></td>

<td>No minimum requirement. Start up scripts are included as shell scripts and Windows batch files.</td>
            </tr>
          </table>

      </div>


<div class="section">
<h3><a name="Files"></a>Files</h3>

<p>Maven is distributed in several formats for your convenience. Simply pick a
      ready-made binary distribution archive and follow the <a href="./install.html">
      installation instructions.</a>
      Use a source archive if you intend to build Maven yourself.</p>

<p>
      In order to guard against corrupted downloads/installations, it is highly recommended to
      <a class="externalLink" href="https://www.apache.org/dev/release-signing#verifying-signature">verify the signature</a>
      of the release bundles against the public <a class="externalLink" href="https://www.apache.org/dist/maven/KEYS">KEYS</a> used by the Apache Maven
      developers.</p>

<table border="0" class="table table-striped">
        <thead>

<tr class="a">

<th></th>

<th>Link</th>

<th>Checksum</th>

<th>Signature</th>
          </tr>
        </thead>
        <tbody>

<tr class="b">

<td>Binary tar.gz archive</td>

<td><a href="http://it.apache.contactlab.it/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz">apache-maven-3.5.0-bin.tar.gz</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/mock/binaries/apache-maven-mock-bin.tar.gz.md5">apache-maven-3.5.0-bin.tar.gz.md5</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz.asc">apache-maven-3.5.0-bin.tar.gz.asc</a></td>
          </tr>

<tr class="a">

<td>Binary zip archive</td>

<td><a href="http://it.apache.contactlab.it/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip">apache-maven-3.5.0-bin.zip</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip.md5">apache-maven-3.5.0-bin.zip.md5</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip.asc">apache-maven-3.5.0-bin.zip.asc</a></td>
          </tr>

<tr class="b">

<td>Source tar.gz archive</td>

<td><a href="http://it.apache.contactlab.it/maven/maven-3/3.5.0/source/apache-maven-3.5.0-src.tar.gz">apache-maven-3.5.0-src.tar.gz</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/source/apache-maven-3.5.0-src.tar.gz.md5">apache-maven-3.5.0-src.tar.gz.md5</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/source/apache-maven-3.5.0-src.tar.gz.asc">apache-maven-3.5.0-src.tar.gz.asc</a></td>
          </tr>

<tr class="a">

<td>Source zip archive </td>

<td><a href="http://it.apache.contactlab.it/maven/maven-3/3.5.0/source/apache-maven-3.5.0-src.zip">apache-maven-3.5.0-src.zip</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/source/apache-maven-3.5.0-src.zip.md5">apache-maven-3.5.0-src.zip.md5</a></td>

<td><a class="externalLink" href="https://www.apache.org/dist/maven/maven-3/3.5.0/source/apache-maven-3.5.0-src.zip.asc">apache-maven-3.5.0-src.zip.asc</a></td>
          </tr>
        </tbody>
      </table>

<ul>

<li><a href="./docs/3.5.0/release-notes.html">Release Notes</a></li>

<li><a href="./ref/3.5.0/">Reference Documentation</a></li>

<li><a href="./maven-site-1.0-site.jar">Apache Maven Website As Documentation Archive</a></li>


<li><a href="http://it.apache.contactlab.it//maven/">All sources (plugins, shared libraries,...) available at https://www.apache.org/dist/maven/</a></li>

<li>Distributed under the <a class="externalLink" href="https://www.apache.org/licenses/">Apache License, version 2.0</a></li>
      </ul>
      </div>


<div class="section">
<h3><a name="Previous_Releases"></a>Previous Releases</h3>

<p>It is strongly recommended to use the latest release version of Apache Maven to take advantage of newest features and bug fixes.</p>


<p>If you still want to use an old version you can find more information in the
        <a href="./docs/history.html">Maven Releases History</a> and can download files from
        the  <a class="externalLink" href="https://archive.apache.org/dist/maven/maven-3/">archives</a> for versions 3.0.4+
        and <a class="externalLink" href="https://archive.apache.org/dist/maven/binaries/">legacy archives</a> for earlier releases.</p>
      </div>
    </div>


        </div>
      </div>
    </div>
    <hr/>
    <footer>
      <div class="container-fluid">
        <div class="row-fluid">
            <p>Copyright &copy;2002&#x2013;2017
<a href="https://www.apache.org/">The Apache Software Foundation</a>.
All rights reserved.</p>
        </div>
        </div>
    </footer>
    </body>
</html>

